// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfOttyPTG4nBQQl6r138XtxsdnSuMEdTQ',
    appId: '1:430639775418:web:ac67f9aeb96e3b26af0c83',
    messagingSenderId: '430639775418',
    projectId: 'onetap-dc5a5',
    authDomain: 'onetap-dc5a5.firebaseapp.com',
    storageBucket: 'onetap-dc5a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtX4Pg16wL_SbhUYspjR_9X51MLoNiz_8',
    appId: '1:430639775418:android:bae5f7336933287aaf0c83',
    messagingSenderId: '430639775418',
    projectId: 'onetap-dc5a5',
    storageBucket: 'onetap-dc5a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQknjASXzhMVgDt6-1r7H9BlbxkAbijeI',
    appId: '1:430639775418:ios:b4c78b559509a436af0c83',
    messagingSenderId: '430639775418',
    projectId: 'onetap-dc5a5',
    storageBucket: 'onetap-dc5a5.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQknjASXzhMVgDt6-1r7H9BlbxkAbijeI',
    appId: '1:430639775418:ios:8bfbdb13362d6df9af0c83',
    messagingSenderId: '430639775418',
    projectId: 'onetap-dc5a5',
    storageBucket: 'onetap-dc5a5.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
